language: android
jdk: oraclejdk8
sudo: false

env:
 global:
 - ANDROID_API=9
 - ANDROID_BUILD_TOOLS=19.1.0
 - ADB_INSTALL_TIMEOUT=5

before_install:
  - openssl aes-256-cbc -K $encrypted_041794058c4d_key -iv $encrypted_041794058c4d_iv -in iCCTVKeyStore.jks.enc -out iCCTVKeyStore.jks -d

install:
  - bash ./ci/install.sh

before_deploy:
  - KEY_ALIAS=iCCTV bash ./ci/sign.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

script: echo "Skipping Tests"

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

dd:
  secure: DbfzW47kzgmX7kMHyzzdy4zOsArVuviQb8CABEzKS5a73IzbvchDU6NU/l6aC8V3v5+QCUPd6/khXy+hzXlJIMFjACAuimPgbQd5vEcnZveRUW/n1WGTYUtpzDf/15nbBH5DInpD4l20AYmQJUyl+Haw22F9ytYlDu0VNhTMAjXce+ala7bUB4OWIj07aNnbkjGCOLx21GXiyut7JvpyjDeTngh53azqHXMNmjqnCbTp/zpREsozj1XNfxzZ2vBdAIkDN9EyVAOmzQd7jYi6F7R2uG7DP2OQyBau15tm+Oj3sE97RYDgQL/X0h8VXA32xZmrX6mzRaF3c54vViggVQSbgZCfKtL60CEmQGB4HkHYPY+b7s8X2r7mrW6NR3vFVXlnjus+Gq7DoG1bJUx7VwC8HoLSflseR4412E5x1PoBbUluZD6XWYzfjUlH8bb39MRxBmcNeJk3vFAhRj9uYBuTHZl/jsQ2vAlEmeai3+c7gFsdscrZ79MfXiYc4AQEUeaFCy2QW5aVSwXlKI9Txq1uQfs65ckZoqa0TCg/qEerBiCBZU5W4u7Je65C5Hi6jz7ugN5wcs231ruZhoW023YcJTf12rzqiNHWvgkcr1cSyNcfPkE7ZltByexJH8+6Kea4a+WPMSJ3TdaslZCUVE0fryv7ziIZ0mNWdSZcOhY=
