language: android
jdk: oraclejdk8
sudo: false

env:
 global:
 - ANDROID_API=9
 - ANDROID_BUILD_TOOLS=25.0.1
 - APK_NAME=iCCTV.apk
 # Key Password
 - secure: "abNejShMrkly0wPa/Iedg9ZYZcKj19VpgbNdvo/WwhHo0xwFr+ktbz3veHzhGpp0Pg316zjG4K860qo0bdFQW+lSOX8grCHsHQKUsuTLwbt8j5TeUaozlQrSulv7p+zDjaFCUc/Zs1z62k/KpO/5WUNTYJdgfWurNSQjnSrGbHVxi7tRxSCtUoDdgc/jd8YxPNzXy4mzzLrwzWU9CUgi3xyWnsBZJ6X6pVlsnkgwiOvU1bHikaHLgPV7dI/PPAQvm1frP9K2/SJtAb2kQCk9dYiW5KgSDw2uX64k5+0MEMownW567QRMtuHAdMXpEi2atFDbOImXMorRmcWVMY8NlOmBAF+095UmObPnjNiuMWdGS+KIXHr9ZC3zYfBnIt9nu0Zwr2jMnnTWFAxk5oz8q8KQgeKjJ2S+C7JAysj5pbuczZo2yoCge2fxWwkl0arqvrLhnBUsV95PzQUzmT9lRTU/WOOdcPqHdryyk7/XYP8tM52G+PjlQmRALKoMnKxKtsdYQ7tPep7Odq9C/tcR5zTRAnlisas7l65D+YHMATR7oxWUhtX9fgNCbbC9yoXJGL/qBQUB0DhYCCNSnVoIkH1fF/IcilBgZ67s4/eRX9sDekzxIrptT4Jr8JyOqwk4TrPTO5Fw998Un6mxHLpq8r7M7wr35v+hXJgF7tp/KNk="

 # Keystore Password
 - secure: "KI1ukFTn9G/eqXACZoyOym09zuOSH76ddBuRN+x1UJxYW2CFoT+3YTYhHKZK8dZ8ISVG5lPRBG5sA1I+tE+f2FN3fU7reU9IXH/KDyI6mDQ6QtGRiu8IdprNH/PonsbQgD/yPIDZMgotaXkL8t2h8CAXz+ejEYKcYTHeQ+aBoMfnUd667/7Ykr88yC1x7do/0iLv7aaOv+YX4ZfH/80kwI9T2NDAZsjzgfaACngPRj28T3or6q/yiCxucLjWWERStTd/P6n0rnx47G9jyo2KZ7E98KVTLdrO05r0Py6wPphMVrbOgbAE4vhfv6mXNcB/9pAaZ2V6yQaaa0Hf7kcWSREHd7DBpOcj8vavAFkdmOV9tX3d1wgFzuSzEgxrOYwfe4fEXzylhOnsshPKtlUF+9InWrJLa8BqrRsUcXtCeQceSKZdCBufoOb51vDVS99lAHnmOZq55lVhsd9WB2NaofaFP8OCXsKEfsLJvPRM4PU6vKV615AGAUtzE7FF2fsEvCofgts/BLvRisbD6IOgfWXV56OM6RrptSr8ArHYFcL54s98Absw4P04hVIi3ysuLxpCTdYB+oNop0Rug2IQaoQVd9qAr+VgH+f73Cxkf2SO5vvVCXX+Fn0z2N/2Ze3vSVeE5UQMvRBEpKCLULvBknpive50YwpANQLQsMykHOU="

before_install:
  - openssl aes-256-cbc -K $encrypted_041794058c4d_key -iv $encrypted_041794058c4d_iv -in iCCTVKeyStore.jks.enc -out iCCTVKeyStore.jks -d

install:
  - bash ./ci/install.sh

before_deploy:
  - KEYSTORE_FILE=iCCTVKeyStore.jks KEY_ALIAS=iCCTV bash ./ci/sign.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

script:
  - ./gradlew clean build

deploy:
  provider: releases
  file: iCCCTV.apk
  skip_cleanup: true
  on:
    branch: master
  api_key:
    secure: "I0F6q8TIkj7G1e1PDcnX+McePGqx+OSzM7GOaOIzqLGgM92+e6qTfk3h5TSaoYXHO3PWuWmD5yd6glv/XnNUL1KTGp+vvPbBNBlmb7fuN2pt59R/50tbUk/a1C2/hEcRrq1Ml2mD8K6gG8S4tglSm7kRdKU0AhiRgaDMjkzIg2lFpJytlAiVHVb3J3YJ4A6DUupXdIBvXEev4kcS/3ietsz9RyRjt9nA1qFvxlP+KJaYq2tT6vSaSgD0vNwUQZ2Y6yoM8CPchyZqxXKE9RJvDQsN/1u4w6itoVHZ0vyhoG0K7xLrLpdK6ir6Jw7qEUB4/JgZiJKzLnLQWJk1TATE8BY2zbVGMtya9ToRPTV1lLAkhL5+B1kgmd6HVc2/jmqBq/VkSFJjgBYUBJhdEFuPPPrtfP5i+shhPsBy6hyKcepOaqJjnJYm6K0y+Y1lp/lk4nJDFYPTAtumhsLE1AB2hu8vKnvBBun1shw/hU7yl6/QNSPksogQZYqqny6m1o/a/DYL5QJ8plO8T6Cdl9Xi56BPg8FCkkXi6IYeTLC89Ueh/e8Qk/tRELHUY9LWJ12EYqCi1KcQ7gAO0jZ8cuRreeXZDZRCm6F5NmkOmG57KVIQBh+PveGg/6sKQ2qFLntcTy7nC4tu1r/XSN+IK6dPM1/TVl4TT+IQfxYbXDSCqLM="


cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

dd:
  secure: DbfzW47kzgmX7kMHyzzdy4zOsArVuviQb8CABEzKS5a73IzbvchDU6NU/l6aC8V3v5+QCUPd6/khXy+hzXlJIMFjACAuimPgbQd5vEcnZveRUW/n1WGTYUtpzDf/15nbBH5DInpD4l20AYmQJUyl+Haw22F9ytYlDu0VNhTMAjXce+ala7bUB4OWIj07aNnbkjGCOLx21GXiyut7JvpyjDeTngh53azqHXMNmjqnCbTp/zpREsozj1XNfxzZ2vBdAIkDN9EyVAOmzQd7jYi6F7R2uG7DP2OQyBau15tm+Oj3sE97RYDgQL/X0h8VXA32xZmrX6mzRaF3c54vViggVQSbgZCfKtL60CEmQGB4HkHYPY+b7s8X2r7mrW6NR3vFVXlnjus+Gq7DoG1bJUx7VwC8HoLSflseR4412E5x1PoBbUluZD6XWYzfjUlH8bb39MRxBmcNeJk3vFAhRj9uYBuTHZl/jsQ2vAlEmeai3+c7gFsdscrZ79MfXiYc4AQEUeaFCy2QW5aVSwXlKI9Txq1uQfs65ckZoqa0TCg/qEerBiCBZU5W4u7Je65C5Hi6jz7ugN5wcs231ruZhoW023YcJTf12rzqiNHWvgkcr1cSyNcfPkE7ZltByexJH8+6Kea4a+WPMSJ3TdaslZCUVE0fryv7ziIZ0mNWdSZcOhY=
